
name: myCI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install
        run: make install

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Run linter
        run: make lint
